### ISSUE TITLE
Django version problem(Don tool using 1.7)

### ISSUE THREAD

**Issue by basivireddy** [CiscoSystems/don#12]
Hi my environment Django version 1.6 

> > > import django; print(django.VERSION)
> > > (1, 6, 1, 'final', 0)

so I got this error "ImproperlyConfigured: Module "django.contrib.auth.middleware" does not define a "SessionAuthenticationMiddleware" attribute/class"

solution: 
upgrade Django version 1.6 to 1.7:
pip install django==1.7

**Comment by amsaha** [comment]
Hi,
Thanks. so is the issue resolved after upgrading the Django version?

**Comment by basivireddy** [comment]
Hi Amit Saha,

Yes.The issue resolved.Which Django version are you used ?. You hard code
the server ip on html page , It's not match with views.I am trying to edit
the pages.I am able to see static data.I want dynamic data.

Thanks & Regards ,
Basivireddy Duggempudi

**Comment by amsaha** [comment]
I don't remember which Django version I used. Anyway, good to hear that it works for you know.

I don't think that this code does dynamic data right now. That needs a slightly different infrastructure.
